version: "3"

services:
  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./examples/cet.sql:/docker-entrypoint-initdb.d/cet.sql"
    networks:
      - app
  # app:
  #   build: .
  #   tag:
    
networks:
  app:

volumes:
  postgres-data: