SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
BEGIN;
CREATE TABLE "categories" (
"cid" serial,
"kind" int2,
"domain" int2,
"value" int2,
"description" varchar(100));
ALTER TABLE "categories" ADD PRIMARY KEY (cid);
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','0','Other');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','1','Tank');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','2','Armored Fighting Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','3','Armored Utility Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','4','Self-propelled Artillery');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','5','Towed Artillery');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','6','Small Wheeled Utility Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','7','Large Wheeled Utility Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','8','Small Tracked Utility Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','9','Large Tracked Utility Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','10','Mortar');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','11','Mine Plow');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','12','Mine Rake');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','13','Mine Roller');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','14','Cargo Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','15','Fuel Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','16','Generator Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','17','Water Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','18','Engineer Equipment');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','19','Heavy Equipment Transport Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','20','Maintenance Equipment Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','21','Limber');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','22','Chemical Decontamination Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','23','Warning System');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','24','Train - Engine');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','25','Train - Car');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','26','Train - Caboose');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','27','Civilian Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','28','Air Defense / Missile Defense Unit Equipment');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','29','Command, Control, Communications, and Intelligence (C3I) System');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','30','Operations Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','31','Intelligence Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','32','Surveillance Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','33','Communications Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','34','Command Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','35','C4I Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','36','Control Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','37','Fire Control Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','38','Missile Defense Facility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','39','Field Command Post');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','40','Observation Post');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','50','Unmanned');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','80','Motorcycle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','81','Car');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','82','Bus');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','83','Single Unit Cargo Truck');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','84','Single Unit Utility/Emergency Truck');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','85','Multiple Unit Cargo Truck');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','86','Multiple Unit Utility/Emergency Truck');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','87','Construction Specialty Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','88','Farm Specialty Vehicle');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','89','Trailer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','90','Recreational');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','91','Non-motorized');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','92','Trains');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','1','93','Utility/Emergency Car');
COMMIT;
ANALYZE "categories";
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','0','Other');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','1','Fighter/Air Defense');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','2','Attack/Strike');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','3','Bomber');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','4','Cargo/Tanker');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','5','ASW/Patrol/Observation');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','6','Electronic Warfare (EW)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','7','Reconnaissance');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','8','Surveillance/C2 (Airborne Early Warning)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','9','Air-Sea Rescue (ASR)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','20','Attack Helicopter');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','21','Utility Helicopter');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','22','Anti-Submarine Warfare/Patrol Helicopter');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','23','Cargo Helicopter');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','24','Observation Helicopter');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','25','Special Operations Helicopter');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','40','Trainer');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','50','Unmanned');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','57','Non-Combatant Commercial Aircraft');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','80','Civilian Ultralight Aircraft, Non-rigid Wing');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','81','Civilian Ultralight Aircraft, Rigid Wing');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','83','Civilian Fixed Wing Aircraft, Glider');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','84','Civilian Fixed Wing Aircraft, Light Sport (up to 1320 lbs / 600 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','85','Civilian Fixed Wing Aircraft, Small (up to 12,500 lbs / 5,670 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','86','Civilian Fixed Wing Aircraft, Medium (up to 41,000 lbs / 18,597 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','87','Civilian Fixed Wing Aircraft, Large (up to 255,000 lbs / 115,666 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','88','Civilian Fixed Wing Aircraft, Heavy (above 255,000 lbs / 115,666 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','90','Civilian Helicopter, Small (up to 7,000 lbs / 3,175 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','91','Civilian Helicopter, Medium (up to 20,000 lbs / 9,072 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','92','Civilian Helicopter, Large (above 20,000 lbs / 9,072 kg)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','93','Civilian Autogyro');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','100','Civilian Lighter than Air, Balloon');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','2','101','Civilian Lighter than Air, Airship');
COMMIT;
ANALYZE "categories";
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','0','Other');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','1','Carrier');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','2','Command Ship/Cruiser');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','3','Guided Missile Cruiser');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','4','Guided Missile Destroyer (DDG)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','5','Destroyer (DD)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','6','Guided Missile Frigate (FFG)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','7','Light/Patrol Craft');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','8','Mine Countermeasure Ship/Craft');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','9','Dock Landing Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','10','Tank Landing Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','11','Landing Craft');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','12','Light Carrier');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','13','Cruiser/Helicopter Carrier');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','14','Hydrofoil');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','15','Air Cushion/Surface Effect');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','16','Auxiliary');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','17','Auxiliary, Merchant Marine');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','18','Utility');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','19','Unmanned Surface Vehicle (USV)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','20','Littoral Combat Ships (LCS)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','21','Surveillance Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','50','Frigate (including Corvette)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','51','Battleship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','52','Heavy Cruiser');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','53','Destroyer Tender');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','54','Amphibious Assault Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','55','Amphibious Cargo Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','56','Amphibious Transport Dock');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','57','Ammunition Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','58','Combat Stores Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','59','Surveillance Towed Array Sonar System (SURTASS)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','60','Fast Combat Support Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','61','Non-Combatant Ship');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','62','Coast Guard Cutters');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','63','Coast Guard Boats');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','64','Fast Attack Craft');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','80','Passenger Vessel (Group 1 Merchant)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','81','Dry Cargo Ship (Group 2 Merchant)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','82','Tanker (Group 3 Merchant)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','83','Support Vessel');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','84','Private Motorboat');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','85','Private Sailboat');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','86','Fishing Vessel');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','87','Other Vessels');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','100','Search and Rescue Vessels');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','3','101','Life-Saving Equipment');
COMMIT;
ANALYZE "categories";
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','0','Other');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','1','SSBN (Nuclear Ballistic Missile)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','2','SSGN (Nuclear Guided Missile)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','3','SSN (Nuclear Attack - Torpedo)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','4','SSG (Conventional Guided Missile)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','5','SS (Conventional Attack - Torpedo, Patrol)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','6','SSAN (Nuclear Auxiliary)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','7','SSA (Conventional Auxiliary)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','8','Unmanned Underwater Vehicle (UUV)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','9','SSB (Submarine Ballistic, Ballistic Missile Submarine)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','10','SSC (Coastal Submarine, over 150 tons)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','11','SSP (Attack Submarine - Diesel Air-Independent Propulsion)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','12','SSM (Midget Submarine, under 150 tons)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','13','SSNR (Special Attack Submarine)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','14','SST (Training Submarine)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','15','AGSS (Auxiliary Submarine)');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','16','Semi-Submersible Boats');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','80','Civilian Submarines');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','81','Civilian Submersibles');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','4','82','Civilian Semi-Submersible Boats');
COMMIT;
ANALYZE "categories";
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','5','0','Other');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','5','1','Manned');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','5','2','Unmanned');
INSERT INTO "categories" ("kind","domain","value","description") VALUES ('1','5','3','Booster');
COMMIT;
ANALYZE "categories";
INSERT INTO "categories" ("kind","value","description") VALUES ('2','0','Other');
INSERT INTO "categories" ("kind","value","description") VALUES ('2','1','Guided');
INSERT INTO "categories" ("kind","value","description") VALUES ('2','2','Ballistic');
INSERT INTO "categories" ("kind","value","description") VALUES ('2','3','Fixed');
COMMIT;
ANALYZE "categories";
