SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
BEGIN;
CREATE TABLE "pdus" (
"value" int2,
"description" varchar(50));
ALTER TABLE "pdus" ADD PRIMARY KEY (value);
INSERT INTO "pdus" ("value","description") VALUES ('0','Other');
INSERT INTO "pdus" ("value","description") VALUES ('1','Entity State');
INSERT INTO "pdus" ("value","description") VALUES ('2','Fire');
INSERT INTO "pdus" ("value","description") VALUES ('3','Detonation');
INSERT INTO "pdus" ("value","description") VALUES ('4','Collision');
INSERT INTO "pdus" ("value","description") VALUES ('5','Service Request');
INSERT INTO "pdus" ("value","description") VALUES ('6','Resupply Offer');
INSERT INTO "pdus" ("value","description") VALUES ('7','Resupply Received');
INSERT INTO "pdus" ("value","description") VALUES ('8','Resupply Cancel');
INSERT INTO "pdus" ("value","description") VALUES ('9','Repair Complete');
INSERT INTO "pdus" ("value","description") VALUES ('10','Repair Response');
INSERT INTO "pdus" ("value","description") VALUES ('11','Create Entity');
INSERT INTO "pdus" ("value","description") VALUES ('12','Remove Entity');
INSERT INTO "pdus" ("value","description") VALUES ('13','Start/Resume');
INSERT INTO "pdus" ("value","description") VALUES ('14','Stop/Freeze');
INSERT INTO "pdus" ("value","description") VALUES ('15','Acknowledge');
INSERT INTO "pdus" ("value","description") VALUES ('16','Action Request');
INSERT INTO "pdus" ("value","description") VALUES ('17','Action Response');
INSERT INTO "pdus" ("value","description") VALUES ('18','Data Query');
INSERT INTO "pdus" ("value","description") VALUES ('19','Set Data');
INSERT INTO "pdus" ("value","description") VALUES ('20','Data');
INSERT INTO "pdus" ("value","description") VALUES ('21','Event Report');
INSERT INTO "pdus" ("value","description") VALUES ('22','Comment');
INSERT INTO "pdus" ("value","description") VALUES ('23','Electromagnetic Emission');
INSERT INTO "pdus" ("value","description") VALUES ('24','Designator');
INSERT INTO "pdus" ("value","description") VALUES ('25','Transmitter');
INSERT INTO "pdus" ("value","description") VALUES ('26','Signal');
INSERT INTO "pdus" ("value","description") VALUES ('27','Receiver');
INSERT INTO "pdus" ("value","description") VALUES ('28','IFF');
INSERT INTO "pdus" ("value","description") VALUES ('29','Underwater Acoustic');
INSERT INTO "pdus" ("value","description") VALUES ('30','Supplemental Emission / Entity State');
INSERT INTO "pdus" ("value","description") VALUES ('31','Intercom Signal');
INSERT INTO "pdus" ("value","description") VALUES ('32','Intercom Control');
INSERT INTO "pdus" ("value","description") VALUES ('33','Aggregate State');
INSERT INTO "pdus" ("value","description") VALUES ('34','IsGroupOf');
INSERT INTO "pdus" ("value","description") VALUES ('35','Transfer Ownership');
INSERT INTO "pdus" ("value","description") VALUES ('36','IsPartOf');
INSERT INTO "pdus" ("value","description") VALUES ('37','Minefield State');
INSERT INTO "pdus" ("value","description") VALUES ('38','Minefield Query');
INSERT INTO "pdus" ("value","description") VALUES ('39','Minefield Data');
INSERT INTO "pdus" ("value","description") VALUES ('40','Minefield Response NACK');
INSERT INTO "pdus" ("value","description") VALUES ('41','Environmental Process');
INSERT INTO "pdus" ("value","description") VALUES ('42','Gridded Data');
INSERT INTO "pdus" ("value","description") VALUES ('43','Point Object State');
INSERT INTO "pdus" ("value","description") VALUES ('44','Linear Object State');
INSERT INTO "pdus" ("value","description") VALUES ('45','Areal Object State');
INSERT INTO "pdus" ("value","description") VALUES ('46','TSPI');
INSERT INTO "pdus" ("value","description") VALUES ('47','Appearance');
INSERT INTO "pdus" ("value","description") VALUES ('48','Articulated Parts');
INSERT INTO "pdus" ("value","description") VALUES ('49','LE Fire');
INSERT INTO "pdus" ("value","description") VALUES ('50','LE Detonation');
INSERT INTO "pdus" ("value","description") VALUES ('51','Create Entity-R');
INSERT INTO "pdus" ("value","description") VALUES ('52','Remove Entity-R');
INSERT INTO "pdus" ("value","description") VALUES ('53','Start/Resume-R');
INSERT INTO "pdus" ("value","description") VALUES ('54','Stop/Freeze-R');
INSERT INTO "pdus" ("value","description") VALUES ('55','Acknowledge-R');
INSERT INTO "pdus" ("value","description") VALUES ('56','Action Request-R');
INSERT INTO "pdus" ("value","description") VALUES ('57','Action Response-R');
INSERT INTO "pdus" ("value","description") VALUES ('58','Data Query-R');
INSERT INTO "pdus" ("value","description") VALUES ('59','Set Data-R');
INSERT INTO "pdus" ("value","description") VALUES ('60','Data-R');
INSERT INTO "pdus" ("value","description") VALUES ('61','Event Report-R');
INSERT INTO "pdus" ("value","description") VALUES ('62','Comment-R');
INSERT INTO "pdus" ("value","description") VALUES ('63','Record-R');
INSERT INTO "pdus" ("value","description") VALUES ('64','Set Record-R');
INSERT INTO "pdus" ("value","description") VALUES ('65','Record Query-R');
INSERT INTO "pdus" ("value","description") VALUES ('66','Collision-Elastic');
INSERT INTO "pdus" ("value","description") VALUES ('67','Entity State Update');
INSERT INTO "pdus" ("value","description") VALUES ('68','Directed Energy Fire');
INSERT INTO "pdus" ("value","description") VALUES ('69','Entity Damage Status');
INSERT INTO "pdus" ("value","description") VALUES ('70','Information Operations Action');
INSERT INTO "pdus" ("value","description") VALUES ('71','Information Operations Report');
INSERT INTO "pdus" ("value","description") VALUES ('72','Attribute');
COMMIT;
ANALYZE "pdus";
