SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
BEGIN;
CREATE TABLE "forces" (
"value" int2,
"description" varchar(20));
ALTER TABLE "forces" ADD PRIMARY KEY (value);
INSERT INTO "forces" ("value","description") VALUES ('0','Other');
INSERT INTO "forces" ("value","description") VALUES ('1','Friendly');
INSERT INTO "forces" ("value","description") VALUES ('2','Opposing');
INSERT INTO "forces" ("value","description") VALUES ('3','Neutral');
INSERT INTO "forces" ("value","description") VALUES ('4','Friendly 2');
INSERT INTO "forces" ("value","description") VALUES ('5','Opposing 2');
INSERT INTO "forces" ("value","description") VALUES ('6','Neutral 2');
INSERT INTO "forces" ("value","description") VALUES ('7','Friendly 3');
INSERT INTO "forces" ("value","description") VALUES ('8','Opposing 3');
INSERT INTO "forces" ("value","description") VALUES ('9','Neutral 3');
INSERT INTO "forces" ("value","description") VALUES ('10','Friendly 4');
INSERT INTO "forces" ("value","description") VALUES ('11','Opposing 4');
INSERT INTO "forces" ("value","description") VALUES ('12','Neutral 4');
INSERT INTO "forces" ("value","description") VALUES ('13','Friendly 5');
INSERT INTO "forces" ("value","description") VALUES ('14','Opposing 5');
INSERT INTO "forces" ("value","description") VALUES ('15','Neutral 5');
INSERT INTO "forces" ("value","description") VALUES ('16','Friendly 6');
INSERT INTO "forces" ("value","description") VALUES ('17','Opposing 6');
INSERT INTO "forces" ("value","description") VALUES ('18','Neutral 6');
INSERT INTO "forces" ("value","description") VALUES ('19','Friendly 7');
INSERT INTO "forces" ("value","description") VALUES ('20','Opposing 7');
INSERT INTO "forces" ("value","description") VALUES ('21','Neutral 7');
INSERT INTO "forces" ("value","description") VALUES ('22','Friendly 8');
INSERT INTO "forces" ("value","description") VALUES ('23','Opposing 8');
INSERT INTO "forces" ("value","description") VALUES ('24','Neutral 8');
INSERT INTO "forces" ("value","description") VALUES ('25','Friendly 9');
INSERT INTO "forces" ("value","description") VALUES ('26','Opposing 9');
INSERT INTO "forces" ("value","description") VALUES ('27','Neutral 9');
INSERT INTO "forces" ("value","description") VALUES ('28','Friendly 10');
INSERT INTO "forces" ("value","description") VALUES ('29','Opposing 10');
INSERT INTO "forces" ("value","description") VALUES ('30','Neutral 10');
COMMIT;
ANALYZE "forces";
